### ISSUE TITLE
Edit syntax highlighting colors. 

### ISSUE THREAD

**Issue by rstaples** [DiogoAndre/language-cisco#10]
Hello, bit really an issue but I would like to know where do you pull the colors for the syntax highlighting.  I would like to edit the colors for my own configurations.

**Comment by DiogoAndre** [comment]
Hi @rstaples!

The colors will mostly come from the Themes installed on Atom. So to change the colors, you must customize your theme, or install a new one.

I wrote a blog post a little while ago that partially covers this difference: [Syntax Highlighting For Network Engineers on DevNet Code Exchange](https://blogs.cisco.com/developer/syntax-highlighting-on-code-exchange)

If you want to create or customize a Syntax Theme, you can check Atom's official docs [Creating a Theme](https://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/)

Hope it helps
