### ISSUE TITLE
Request for installation

### ISSUE THREAD

**Issue by alainduperche** [DiogoAndre/language-cisco#7]
Hello,
I need some information for installation, or "how to" documentation.
Thanks.
Alain

**Comment by DiogoAndre** [comment]
Hi Alain. I assume you're using Atom already, right?  The following page has some basic instructions on what are Atom packages and how to install them. [Atom Packages](https://flight-manual.atom.io/using-atom/sections/atom-packages/)

hope it helps!

**Comment by alainduperche** [comment]
Ok, I Try it.

Thanks (Merci).



<http://www.aforp.fr/entreprises/votre-taxe-dapprentissage-pour-soutenir-une-formation-hors-du-commun>
[cid:jpo2018_6217a9f2-29b5-4b99-b423-a4562758f517.jpg]<https://goo.gl/rvwjxx>   [cid:TA2018_0088615f-f838-4a97-a5ff-dfcb44153713.jpg] <https://goo.gl/ZmbTK2>
De : Diogo [mailto:notifications@github.com]
Envoyé : lundi 11 décembre 2017 12:38
À : DiogoAndre/language-cisco <language-cisco@noreply.github.com>
Cc : DUPERCHE Alain <a.duperche@aforp.fr>; Author <author@noreply.github.com>
Objet : Re: [DiogoAndre/language-cisco] Request for installation (#7)


Hi Alain. I assume you're using Atom already, right? The following page has some basic instructions on what are Atom packages and how to install them. Atom Packages<https://flight-manual.atom.io/using-atom/sections/atom-packages/>

hope it helps!
